name: everyday_invest
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: ^5.0.0
  get: ^4.6.5

  # UI Packages
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  google_nav_bar: ^5.0.6
  fl_chart: ^0.65.0

  # Firebase Packages
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.2
  firebase_auth: ^4.15.0

  # Icons Packages
  line_awesome_flutter: ^2.0.0
  line_icons: ^2.0.2
  cupertino_icons: ^1.0.2
  yahoo_finance_data_reader: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding_images/
    - assets/images/profile_page_images/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/logo/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Light.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf

  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
